/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.Navegador;

import java.awt.Color;

/**
 *
 * @author maiko
 */
public class AgendaView extends javax.swing.JFrame {

    private boolean alterado = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgendaView.class.getName());

    /**
     * Creates new form ListaImovelView
     */
    public AgendaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        lblImoveis = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        lblCriativos = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        lblMinhaPagina = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbxMes = new javax.swing.JComboBox<>();
        cbxAno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGrid1 = new javax.swing.JButton();
        btnGrid8 = new javax.swing.JButton();
        btnGrid15 = new javax.swing.JButton();
        btnGrid22 = new javax.swing.JButton();
        btnGrid29 = new javax.swing.JButton();
        btnGrid36 = new javax.swing.JButton();
        btnGrid2 = new javax.swing.JButton();
        btnGrid3 = new javax.swing.JButton();
        btnGrid4 = new javax.swing.JButton();
        btnGrid5 = new javax.swing.JButton();
        btnGrid6 = new javax.swing.JButton();
        btnGrid7 = new javax.swing.JButton();
        btnGrid9 = new javax.swing.JButton();
        btnGrid10 = new javax.swing.JButton();
        btnGrid11 = new javax.swing.JButton();
        btnGrid12 = new javax.swing.JButton();
        btnGrid13 = new javax.swing.JButton();
        btnGrid14 = new javax.swing.JButton();
        btnGrid16 = new javax.swing.JButton();
        btnGrid23 = new javax.swing.JButton();
        btnGrid30 = new javax.swing.JButton();
        btnGrid37 = new javax.swing.JButton();
        btnGrid17 = new javax.swing.JButton();
        btnGrid24 = new javax.swing.JButton();
        btnGrid31 = new javax.swing.JButton();
        btnGrid38 = new javax.swing.JButton();
        btnGrid18 = new javax.swing.JButton();
        btnGrid25 = new javax.swing.JButton();
        btnGrid32 = new javax.swing.JButton();
        btnGrid39 = new javax.swing.JButton();
        btnGrid19 = new javax.swing.JButton();
        btnGrid26 = new javax.swing.JButton();
        btnGrid33 = new javax.swing.JButton();
        btnGrid40 = new javax.swing.JButton();
        btnGrid20 = new javax.swing.JButton();
        btnGrid27 = new javax.swing.JButton();
        btnGrid34 = new javax.swing.JButton();
        btnGrid41 = new javax.swing.JButton();
        btnGrid21 = new javax.swing.JButton();
        btnGrid28 = new javax.swing.JButton();
        btnGrid35 = new javax.swing.JButton();
        btnGrid42 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMenu.setPreferredSize(new java.awt.Dimension(220, 0));

        lblImoveis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImoveis.setText("IMÓVEIS");
        lblImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImoveisMouseClicked(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo120x120.png"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClientes.setText("CLIENTES");
        lblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
        });

        lblAgenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAgenda.setText("MINHA AGENDA");
        lblAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendaMouseClicked(evt);
            }
        });

        lblCriativos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCriativos.setText("CRIATIVOS");
        lblCriativos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCriativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCriativosMouseClicked(evt);
            }
        });

        lblRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRelatorios.setText("RELATÓRIOS");
        lblRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelatoriosMouseClicked(evt);
            }
        });

        lblMinhaPagina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinhaPagina.setText("MINHA PÁGINA");
        lblMinhaPagina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinhaPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinhaPaginaMouseClicked(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuarios.setText("USUÁRIOS");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImoveis)
                    .addComponent(lblAgenda)
                    .addComponent(lblMinhaPagina)
                    .addComponent(lblRelatorios)
                    .addComponent(lblCriativos)
                    .addComponent(lblClientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImoveis)
                .addGap(18, 18, 18)
                .addComponent(lblClientes)
                .addGap(18, 18, 18)
                .addComponent(lblCriativos)
                .addGap(12, 12, 12)
                .addComponent(lblAgenda)
                .addGap(18, 18, 18)
                .addComponent(lblMinhaPagina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuarios)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        cbxMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));

        cbxAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Dom");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Seg");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Ter");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Qui");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Qua");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Sex");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Sab");

        btnGrid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid1ActionPerformed(evt);
            }
        });

        btnGrid8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid8ActionPerformed(evt);
            }
        });

        btnGrid15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid15ActionPerformed(evt);
            }
        });

        btnGrid22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid22ActionPerformed(evt);
            }
        });

        btnGrid29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid29ActionPerformed(evt);
            }
        });

        btnGrid36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid36ActionPerformed(evt);
            }
        });

        btnGrid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid2ActionPerformed(evt);
            }
        });

        btnGrid3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid3ActionPerformed(evt);
            }
        });

        btnGrid4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid4ActionPerformed(evt);
            }
        });

        btnGrid5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid5ActionPerformed(evt);
            }
        });

        btnGrid6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid6ActionPerformed(evt);
            }
        });

        btnGrid7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid7ActionPerformed(evt);
            }
        });

        btnGrid9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid9ActionPerformed(evt);
            }
        });

        btnGrid10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid10ActionPerformed(evt);
            }
        });

        btnGrid11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid11ActionPerformed(evt);
            }
        });

        btnGrid12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid12ActionPerformed(evt);
            }
        });

        btnGrid13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid13ActionPerformed(evt);
            }
        });

        btnGrid14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid14ActionPerformed(evt);
            }
        });

        btnGrid16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid16ActionPerformed(evt);
            }
        });

        btnGrid23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid23ActionPerformed(evt);
            }
        });

        btnGrid30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid30ActionPerformed(evt);
            }
        });

        btnGrid37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid37ActionPerformed(evt);
            }
        });

        btnGrid17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid17ActionPerformed(evt);
            }
        });

        btnGrid24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid24ActionPerformed(evt);
            }
        });

        btnGrid31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid31ActionPerformed(evt);
            }
        });

        btnGrid38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid38ActionPerformed(evt);
            }
        });

        btnGrid18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid18ActionPerformed(evt);
            }
        });

        btnGrid25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid25ActionPerformed(evt);
            }
        });

        btnGrid32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid32ActionPerformed(evt);
            }
        });

        btnGrid39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid39ActionPerformed(evt);
            }
        });

        btnGrid19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid19ActionPerformed(evt);
            }
        });

        btnGrid26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid26ActionPerformed(evt);
            }
        });

        btnGrid33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid33ActionPerformed(evt);
            }
        });

        btnGrid40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid40ActionPerformed(evt);
            }
        });

        btnGrid20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid20ActionPerformed(evt);
            }
        });

        btnGrid27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid27ActionPerformed(evt);
            }
        });

        btnGrid34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid34ActionPerformed(evt);
            }
        });

        btnGrid41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid41ActionPerformed(evt);
            }
        });

        btnGrid21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid21ActionPerformed(evt);
            }
        });

        btnGrid28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid28ActionPerformed(evt);
            }
        });

        btnGrid35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid35ActionPerformed(evt);
            }
        });

        btnGrid42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrid42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGrid42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrid42ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(btnGrid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid29, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(btnGrid2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid16, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(btnGrid23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrid37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnGrid36, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(btnGrid3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnGrid10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnGrid4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrid11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(btnGrid5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnGrid12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(btnGrid6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnGrid13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGrid7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(btnGrid14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrid42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrid1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrid8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrid15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrid22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrid29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrid36, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid37, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid38, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid39, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid40, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid41, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrid42, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1256, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImoveisMouseClicked
        Navegador.abrirTela(this, new ListaImovelView(), alterado);
    }//GEN-LAST:event_lblImoveisMouseClicked

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
        Navegador.abrirTela(this, new ClienteView(), alterado);
    }//GEN-LAST:event_lblClientesMouseClicked

    private void lblCriativosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriativosMouseClicked
        Navegador.abrirTela(this, new CriativosView(), alterado);
    }//GEN-LAST:event_lblCriativosMouseClicked

    private void lblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMouseClicked
        Navegador.abrirTela(this, new AgendaView(), alterado);
    }//GEN-LAST:event_lblAgendaMouseClicked

    private void lblMinhaPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinhaPaginaMouseClicked
        Navegador.abrirTela(this, new MinhaPaginaView(), alterado);
    }//GEN-LAST:event_lblMinhaPaginaMouseClicked

    private void lblRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelatoriosMouseClicked
        Navegador.abrirTela(this, new RelatoriosView(), alterado);
    }//GEN-LAST:event_lblRelatoriosMouseClicked

    private void btnGrid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid1ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid1ActionPerformed

    private void btnGrid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid8ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid8ActionPerformed

    private void btnGrid15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid15ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid15ActionPerformed

    private void btnGrid22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid22ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid22ActionPerformed

    private void btnGrid29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid29ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid29ActionPerformed

    private void btnGrid36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid36ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid36ActionPerformed

    private void btnGrid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid2ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid2ActionPerformed

    private void btnGrid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid3ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid3ActionPerformed

    private void btnGrid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid4ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid4ActionPerformed

    private void btnGrid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid5ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid5ActionPerformed

    private void btnGrid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid6ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid6ActionPerformed

    private void btnGrid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid7ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid7ActionPerformed

    private void btnGrid9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid9ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid9ActionPerformed

    private void btnGrid10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid10ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid10ActionPerformed

    private void btnGrid11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid11ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid11ActionPerformed

    private void btnGrid12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid12ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid12ActionPerformed

    private void btnGrid13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid13ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid13ActionPerformed

    private void btnGrid14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid14ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid14ActionPerformed

    private void btnGrid16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid16ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid16ActionPerformed

    private void btnGrid23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid23ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid23ActionPerformed

    private void btnGrid30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid30ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid30ActionPerformed

    private void btnGrid37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid37ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid37ActionPerformed

    private void btnGrid17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid17ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid17ActionPerformed

    private void btnGrid24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid24ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid24ActionPerformed

    private void btnGrid31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid31ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid31ActionPerformed

    private void btnGrid38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid38ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid38ActionPerformed

    private void btnGrid18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid18ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid18ActionPerformed

    private void btnGrid25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid25ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid25ActionPerformed

    private void btnGrid32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid32ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid32ActionPerformed

    private void btnGrid39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid39ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid39ActionPerformed

    private void btnGrid19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid19ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid19ActionPerformed

    private void btnGrid26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid26ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid26ActionPerformed

    private void btnGrid33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid33ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid33ActionPerformed

    private void btnGrid40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid40ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid40ActionPerformed

    private void btnGrid20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid20ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid20ActionPerformed

    private void btnGrid27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid27ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid27ActionPerformed

    private void btnGrid34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid34ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid34ActionPerformed

    private void btnGrid41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid41ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid41ActionPerformed

    private void btnGrid21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid21ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid21ActionPerformed

    private void btnGrid28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid28ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid28ActionPerformed

    private void btnGrid35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid35ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid35ActionPerformed

    private void btnGrid42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrid42ActionPerformed
        Navegador.abrirTela(this, new AgendaModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrid42ActionPerformed

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgendaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrid1;
    private javax.swing.JButton btnGrid10;
    private javax.swing.JButton btnGrid11;
    private javax.swing.JButton btnGrid12;
    private javax.swing.JButton btnGrid13;
    private javax.swing.JButton btnGrid14;
    private javax.swing.JButton btnGrid15;
    private javax.swing.JButton btnGrid16;
    private javax.swing.JButton btnGrid17;
    private javax.swing.JButton btnGrid18;
    private javax.swing.JButton btnGrid19;
    private javax.swing.JButton btnGrid2;
    private javax.swing.JButton btnGrid20;
    private javax.swing.JButton btnGrid21;
    private javax.swing.JButton btnGrid22;
    private javax.swing.JButton btnGrid23;
    private javax.swing.JButton btnGrid24;
    private javax.swing.JButton btnGrid25;
    private javax.swing.JButton btnGrid26;
    private javax.swing.JButton btnGrid27;
    private javax.swing.JButton btnGrid28;
    private javax.swing.JButton btnGrid29;
    private javax.swing.JButton btnGrid3;
    private javax.swing.JButton btnGrid30;
    private javax.swing.JButton btnGrid31;
    private javax.swing.JButton btnGrid32;
    private javax.swing.JButton btnGrid33;
    private javax.swing.JButton btnGrid34;
    private javax.swing.JButton btnGrid35;
    private javax.swing.JButton btnGrid36;
    private javax.swing.JButton btnGrid37;
    private javax.swing.JButton btnGrid38;
    private javax.swing.JButton btnGrid39;
    private javax.swing.JButton btnGrid4;
    private javax.swing.JButton btnGrid40;
    private javax.swing.JButton btnGrid41;
    private javax.swing.JButton btnGrid42;
    private javax.swing.JButton btnGrid5;
    private javax.swing.JButton btnGrid6;
    private javax.swing.JButton btnGrid7;
    private javax.swing.JButton btnGrid8;
    private javax.swing.JButton btnGrid9;
    private javax.swing.JComboBox<String> cbxAno;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCriativos;
    private javax.swing.JLabel lblImoveis;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinhaPagina;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
