/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.Navegador;

/**
 *
 * @author maiko
 */
public class AgendaModal extends javax.swing.JFrame {

    private boolean alterado = false;
    private java.time.LocalDate data = java.time.LocalDate.now();
    private java.util.List<model.AgendaModel> tarefas = new java.util.ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgendaModal.class.getName());

    /**
     * Creates new form AgendaModal
     */
    public AgendaModal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tblAgenda.setDefaultEditor(Object.class, null);
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) { if (e.getClickCount() == 2) editarSelecionada(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        lblDataAgenda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgendarTarefa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hora", "Tipo", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tblAgenda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 300));

        lblDataAgenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblDataAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 160, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("AGENDAMENTOS DO DIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        btnAgendarTarefa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgendarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAgendarTarefa.setText("Agendar Tarefa");
        btnAgendarTarefa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAgendarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarTarefaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendarTarefa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgendarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarTarefaActionPerformed
        abrirEditor(null);
    }//GEN-LAST:event_btnAgendarTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgendaModal().setVisible(true));
    }


    public AgendaModal(java.time.LocalDate data) {
        this(); this.data = data; carregar();
    }
    private void carregar() {
        lblDataAgenda.setText(data.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        try {
            tarefas = new dao.AgendaDao().listar(data, data);
            javax.swing.table.DefaultTableModel tabela = new javax.swing.table.DefaultTableModel(new String[]{"Horário", "Tipo", "Descrição", "Situação"}, 0) {
                public boolean isCellEditable(int r, int c) { return false; }
            };
            for (model.AgendaModel t : tarefas) tabela.addRow(new Object[]{t.getHorario(), t.getTipo(), t.getDescricao(), t.isConcluida() ? "Concluída" : "Pendente"});
            tblAgenda.setModel(tabela);
        } catch (RuntimeException e) { javax.swing.JOptionPane.showMessageDialog(this, e.getMessage()); }
    }
    private void abrirEditor(model.AgendaModel tarefa) {
        AgendaHoraModal editor = new AgendaHoraModal(data, tarefa);
        editor.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e) { carregar(); }
        });
        editor.setVisible(true);
    }
    private void editarSelecionada() {
        int linha = tblAgenda.getSelectedRow();
        if (linha < 0) return;
        model.AgendaModel tarefa = tarefas.get(tblAgenda.convertRowIndexToModel(linha));
        Object[] opcoes = {"Editar", tarefa.isConcluida() ? "Reabrir" : "Concluir", "Excluir", "Cancelar"};
        int escolha = javax.swing.JOptionPane.showOptionDialog(this, tarefa.getDescricao(), "Tarefa", javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
        try {
            if (escolha == 0) abrirEditor(tarefa);
            else if (escolha == 1) { tarefa.setConcluida(!tarefa.isConcluida()); new controller.AgendaController().salvar(tarefa); carregar(); }
            else if (escolha == 2 && javax.swing.JOptionPane.showConfirmDialog(this, "Excluir esta tarefa?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION) { new dao.AgendaDao().excluir(tarefa.getId()); carregar(); }
        } catch (RuntimeException e) { javax.swing.JOptionPane.showMessageDialog(this, e.getMessage()); }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarTarefa;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataAgenda;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables
}
