package view;

import dao.ClienteDao;
import java.awt.Color;
import util.Navegador;
import dao.ImovelDao;
import static java.lang.Integer.parseInt;
import model.ImovelModel;
import javax.swing.JOptionPane;
import model.ClienteModel;
import model.ClientePfModel;
import model.ClientePjModel;
import util.SessaoUsuario;

/**
 *
 * @author Maikon
 */
public class NovoImovelView extends javax.swing.JFrame {

    private boolean alterado = false;
    private ClienteModel proprietarioSelecionado;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NovoImovelView.class.getName());

    /**
     * Creates new form ListaImovelView
     */
    public NovoImovelView() {
        initComponents();
        lblUsuarios.setVisible(
                SessaoUsuario.isAdministrador()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        lblImoveis = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        lblCriativos = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        lblMinhaPagina = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bntAddFotos = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtDorm = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtSl = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtBanh = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtLav = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtSuite = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtSac = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtGar = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtIdGar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtArTot = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtArPriv = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtArLt = new javax.swing.JTextField();
        rbPatio = new javax.swing.JRadioButton();
        rbPiscinaCasa = new javax.swing.JRadioButton();
        rbVaranda = new javax.swing.JRadioButton();
        rbGradeado = new javax.swing.JRadioButton();
        rbMurado = new javax.swing.JRadioButton();
        rbAlarme = new javax.swing.JRadioButton();
        rbQuiosqueCasa = new javax.swing.JRadioButton();
        rbCanil = new javax.swing.JRadioButton();
        rbPortao = new javax.swing.JRadioButton();
        rbElevador = new javax.swing.JRadioButton();
        rbPortaria = new javax.swing.JRadioButton();
        rbPorteiro = new javax.swing.JRadioButton();
        rbPiscinaCond = new javax.swing.JRadioButton();
        rbQuiosqueCond = new javax.swing.JRadioButton();
        rbPlayground = new javax.swing.JRadioButton();
        rbSalaoFestas = new javax.swing.JRadioButton();
        rbBrinquedoteca = new javax.swing.JRadioButton();
        rbQuadraEsportes = new javax.swing.JRadioButton();
        rbchurrasqueira = new javax.swing.JRadioButton();
        rbLavanderiaCon = new javax.swing.JRadioButton();
        rbAcademia = new javax.swing.JRadioButton();
        rbEspacoPet = new javax.swing.JRadioButton();
        rbCoworking = new javax.swing.JRadioButton();
        rbCamera = new javax.swing.JRadioButton();
        btnAddDocs = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbxStatusImovel = new javax.swing.JComboBox<>();
        cbxTipoImovel = new javax.swing.JComboBox<>();
        btnNovoCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtResponsavel = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtValidade = new javax.swing.JTextField();
        txtDtEntrada = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        lblProprietario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvarImovel = new javax.swing.JButton();
        btnCancelarImovel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtAdm = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtValorCond = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtValorIptu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNegociacao = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taApresentacao = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        cbxTransacao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMenu.setPreferredSize(new java.awt.Dimension(220, 0));

        lblImoveis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImoveis.setText("IMÓVEIS");
        lblImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImoveisMouseClicked(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo120x120.png"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClientes.setText("CLIENTES");
        lblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
        });

        lblAgenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAgenda.setText("MINHA AGENDA");
        lblAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendaMouseClicked(evt);
            }
        });

        lblCriativos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCriativos.setText("CRIATIVOS");
        lblCriativos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCriativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCriativosMouseClicked(evt);
            }
        });

        lblRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRelatorios.setText("RELATÓRIOS");
        lblRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelatoriosMouseClicked(evt);
            }
        });

        lblMinhaPagina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinhaPagina.setText("MINHA PÁGINA");
        lblMinhaPagina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinhaPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinhaPaginaMouseClicked(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuarios.setText("USUÁRIOS");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios)
                    .addComponent(lblImoveis)
                    .addComponent(lblAgenda)
                    .addComponent(lblMinhaPagina)
                    .addComponent(lblRelatorios)
                    .addComponent(lblCriativos)
                    .addComponent(lblClientes)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImoveis)
                .addGap(18, 18, 18)
                .addComponent(lblClientes)
                .addGap(18, 18, 18)
                .addComponent(lblCriativos)
                .addGap(12, 12, 12)
                .addComponent(lblAgenda)
                .addGap(18, 18, 18)
                .addComponent(lblMinhaPagina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRelatorios)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarios)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jPanel2CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        bntAddFotos.setBackground(new java.awt.Color(0, 0, 0));
        bntAddFotos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bntAddFotos.setForeground(new java.awt.Color(255, 255, 255));
        bntAddFotos.setText("Adicionar Fotos");
        bntAddFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddFotosActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setText("Características Internas ");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel19.setText("Características Externas  ");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel20.setText("Características Condominiais");

        jLabel27.setText("Dormitórios:");

        jLabel28.setText("Sala:");

        jLabel29.setText("Banheiros:");

        jLabel30.setText("Suítes:");

        jLabel31.setText("Sacada:");

        jLabel32.setText("Lavanderia:");

        jLabel33.setText("Identificação garagens:");

        jLabel34.setText("Garagem:");

        jLabel35.setText("Área Total: (m²)");

        jLabel36.setText("Área Privativa: (m²)");

        jLabel37.setText("Área Lote: (m²)");

        rbPatio.setText("Pátio");

        rbPiscinaCasa.setText("Piscina");
        rbPiscinaCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPiscinaCasaActionPerformed(evt);
            }
        });

        rbVaranda.setText("Varanda");

        rbGradeado.setText("Gradeado");

        rbMurado.setText("Murado");
        rbMurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMuradoActionPerformed(evt);
            }
        });

        rbAlarme.setText("Alarme");
        rbAlarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlarmeActionPerformed(evt);
            }
        });

        rbQuiosqueCasa.setText("Quiosque");

        rbCanil.setText("Canil");

        rbPortao.setText("Portão Eletrônico");

        rbElevador.setText("Elevador");

        rbPortaria.setText("Portaria");
        rbPortaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPortariaActionPerformed(evt);
            }
        });

        rbPorteiro.setText("Porteiro");
        rbPorteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPorteiroActionPerformed(evt);
            }
        });

        rbPiscinaCond.setText("Piscina");
        rbPiscinaCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPiscinaCondActionPerformed(evt);
            }
        });

        rbQuiosqueCond.setText("Quiosque");
        rbQuiosqueCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuiosqueCondActionPerformed(evt);
            }
        });

        rbPlayground.setText("Playground");
        rbPlayground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlaygroundActionPerformed(evt);
            }
        });

        rbSalaoFestas.setText("Salão de Festas");
        rbSalaoFestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalaoFestasActionPerformed(evt);
            }
        });

        rbBrinquedoteca.setText("Brinquedoteca");
        rbBrinquedoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBrinquedotecaActionPerformed(evt);
            }
        });

        rbQuadraEsportes.setText("Quadra Esportiva");
        rbQuadraEsportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuadraEsportesActionPerformed(evt);
            }
        });

        rbchurrasqueira.setText("Churrasqueiras");
        rbchurrasqueira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbchurrasqueiraActionPerformed(evt);
            }
        });

        rbLavanderiaCon.setText("Lavanderia");
        rbLavanderiaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLavanderiaConActionPerformed(evt);
            }
        });

        rbAcademia.setText("Academia");
        rbAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAcademiaActionPerformed(evt);
            }
        });

        rbEspacoPet.setText("Espaço PET");
        rbEspacoPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEspacoPetActionPerformed(evt);
            }
        });

        rbCoworking.setText("Coworking");
        rbCoworking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCoworkingActionPerformed(evt);
            }
        });

        rbCamera.setText("Câmeras");
        rbCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCameraActionPerformed(evt);
            }
        });

        btnAddDocs.setBackground(new java.awt.Color(0, 0, 0));
        btnAddDocs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddDocs.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDocs.setText("Adicionar Documentos");
        btnAddDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbPorteiro)
                                .addGap(18, 18, 18)
                                .addComponent(rbQuiosqueCond)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(rbPortaria)
                                .addGap(18, 18, 18)
                                .addComponent(rbPiscinaCond)))
                        .addComponent(rbBrinquedoteca))
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDorm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel28)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArPriv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdGar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArTot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArLt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbPiscinaCasa)
                                        .addGap(115, 115, 115))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(rbVaranda)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbQuiosqueCasa))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(rbPatio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbMurado)
                                                .addComponent(rbGradeado)))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(bntAddFotos)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAlarme)
                            .addComponent(rbCanil)
                            .addComponent(rbPortao)))
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbElevador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPlayground)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbSalaoFestas)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(btnAddDocs))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbAcademia))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(rbLavanderiaCon))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbchurrasqueira)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbQuadraEsportes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCoworking))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCamera)
                                    .addComponent(rbEspacoPet))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtDorm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtBanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtIdGar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30)
                    .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txtSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArLt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(txtArPriv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txtArTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPatio)
                    .addComponent(rbGradeado)
                    .addComponent(rbAlarme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPiscinaCasa)
                    .addComponent(rbMurado)
                    .addComponent(rbCanil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVaranda)
                    .addComponent(rbPortao)
                    .addComponent(rbQuiosqueCasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbElevador)
                    .addComponent(rbPlayground)
                    .addComponent(rbQuadraEsportes)
                    .addComponent(rbchurrasqueira)
                    .addComponent(rbCoworking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPortaria)
                    .addComponent(rbPiscinaCond)
                    .addComponent(rbSalaoFestas)
                    .addComponent(rbAcademia)
                    .addComponent(rbEspacoPet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPorteiro)
                    .addComponent(rbQuiosqueCond)
                    .addComponent(rbBrinquedoteca)
                    .addComponent(rbLavanderiaCon)
                    .addComponent(rbCamera))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAddFotos)
                    .addComponent(btnAddDocs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        cbxStatusImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", "Vendido", "Alugado" }));
        cbxStatusImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStatusImovelActionPerformed(evt);
            }
        });

        cbxTipoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Terreno", "Sala Comercial", "Loja" }));
        cbxTipoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoImovelActionPerformed(evt);
            }
        });

        btnNovoCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnNovoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoCliente.setText("Adicionar Cliente");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo");

        jLabel6.setText("CEP");

        jLabel7.setText("Endereço");

        jLabel8.setText("Proprietário");

        jLabel9.setText("Validade");

        jLabel10.setText("Status");

        jLabel11.setText("Data de entrada");

        jLabel12.setText("Responsável");

        jLabel13.setText("Número");

        jLabel14.setText("Complemento");

        jLabel15.setText("Bairro");

        jLabel16.setText("Estado");

        jLabel17.setText("Cidade");

        lblProprietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProprietario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel7))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtEndereco))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnNovoCliente)
                                .addGap(20, 20, 20)
                                .addComponent(lblProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addComponent(jLabel6))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStatusImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbxStatusImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnNovoCliente)
                    .addComponent(lblProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Características e Valores:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Principal");

        btnSalvarImovel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvarImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnSalvarImovel.setText("Salvar Imóvel");
        btnSalvarImovel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSalvarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarImovelActionPerformed(evt);
            }
        });

        btnCancelarImovel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarImovel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarImovel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarImovel.setText("Cancelar");
        btnCancelarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarImovelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("NOVO CADASTRO DE IMÓVEL");

        jLabel22.setText("Valor:");

        jLabel23.setText("Valor de Condomínio:");

        jLabel24.setText("Adminstradora:");

        jLabel25.setText("Valor de IPTU: (parcela)");

        taNegociacao.setColumns(20);
        taNegociacao.setRows(5);
        jScrollPane2.setViewportView(taNegociacao);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel26.setText("Negociação e detalhes financeiros:");

        taApresentacao.setColumns(20);
        taApresentacao.setRows(5);
        jScrollPane1.setViewportView(taApresentacao);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setText("Apresentação:");

        cbxTransacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTransacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venda", "Locação", "Venda e Locação" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Transação:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtValorIptu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtValorCond, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(cbxTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtValorIptu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnCancelarImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78)
                            .addComponent(btnSalvarImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarImovel)
                    .addComponent(btnSalvarImovel))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImoveisMouseClicked
        Navegador.abrirTela(this, new ListaImovelView(), alterado);
    }//GEN-LAST:event_lblImoveisMouseClicked

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
        Navegador.abrirTela(this, new ClienteView(), alterado);
    }//GEN-LAST:event_lblClientesMouseClicked

    private void lblCriativosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriativosMouseClicked
        Navegador.abrirTela(this, new CriativosView(), alterado);
    }//GEN-LAST:event_lblCriativosMouseClicked

    private void lblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMouseClicked
        Navegador.abrirTela(this, new AgendaView(), alterado);
    }//GEN-LAST:event_lblAgendaMouseClicked

    private void lblMinhaPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinhaPaginaMouseClicked
        Navegador.abrirTela(this, new MinhaPaginaView(), alterado);
    }//GEN-LAST:event_lblMinhaPaginaMouseClicked

    private void lblRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelatoriosMouseClicked
        Navegador.abrirTela(this, new RelatoriosView(), alterado);
    }//GEN-LAST:event_lblRelatoriosMouseClicked

    private void jPanel2CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel2CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2CaretPositionChanged

    private void cbxTipoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoImovelActionPerformed

    private void cbxStatusImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatusImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStatusImovelActionPerformed

    private void rbPiscinaCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPiscinaCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPiscinaCasaActionPerformed

    private void rbMuradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMuradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMuradoActionPerformed

    private void rbPortariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPortariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPortariaActionPerformed

    private void rbPorteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPorteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPorteiroActionPerformed

    private void rbPiscinaCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPiscinaCondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPiscinaCondActionPerformed

    private void rbQuiosqueCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuiosqueCondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbQuiosqueCondActionPerformed

    private void rbPlaygroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlaygroundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPlaygroundActionPerformed

    private void rbSalaoFestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalaoFestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSalaoFestasActionPerformed

    private void rbBrinquedotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBrinquedotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBrinquedotecaActionPerformed

    private void rbQuadraEsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuadraEsportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbQuadraEsportesActionPerformed

    private void rbchurrasqueiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbchurrasqueiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbchurrasqueiraActionPerformed

    private void rbLavanderiaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLavanderiaConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLavanderiaConActionPerformed

    private void rbAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAcademiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAcademiaActionPerformed

    private void rbEspacoPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEspacoPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEspacoPetActionPerformed

    private void rbCoworkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCoworkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCoworkingActionPerformed

    private void rbCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCameraActionPerformed

    private void rbAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlarmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAlarmeActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        SelecionarClienteView view
                = new SelecionarClienteView(this);

        view.setVisible(true);
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void bntAddFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddFotosActionPerformed
        Navegador.abrirTela(this, new FotosModal(), alterado);
    }//GEN-LAST:event_bntAddFotosActionPerformed

    private void btnAddDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocsActionPerformed
        Navegador.abrirTela(this, new DocumentosModal(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDocsActionPerformed

    private void btnSalvarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarImovelActionPerformed
        salvarImovel();
    }//GEN-LAST:event_btnSalvarImovelActionPerformed

    private void btnCancelarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarImovelActionPerformed
        Navegador.abrirTela(this, new ListaImovelView(), alterado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarImovelActionPerformed

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
        Navegador.abrirTela(this, new ListaUsuarioModal(), alterado);
    }//GEN-LAST:event_lblUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NovoImovelView().setVisible(true));
    }

    public void setProprietarioSelecionado(
            ClienteModel cliente) {

        this.proprietarioSelecionado = cliente;

        if (cliente instanceof ClientePfModel pf) {

            lblProprietario.setText(
                    pf.getNome());

        } else if (cliente instanceof ClientePjModel pj) {

            lblProprietario.setText(
                    pj.getRazaoSocial());

        }

    }

    private void salvarImovel() {

        try {
            if (proprietarioSelecionado == null) {
                JOptionPane.showMessageDialog(this, "Selecione um proprietário.");
                return;
            }

            ImovelModel imovel = new ImovelModel();

            imovel.setTipoImovel(cbxTipoImovel.getSelectedItem().toString());
            imovel.setTransacao(cbxTransacao.getSelectedItem().toString());
            imovel.setStatusImovel(cbxStatusImovel.getSelectedItem().toString());

            imovel.setEndereco(txtEndereco.getText());
            imovel.setNumero(txtNumero.getText());
            imovel.setComplemento(txtComplemento.getText());
            imovel.setBairro(txtBairro.getText());
            imovel.setCidade(txtCidade.getText());
            imovel.setEstado(txtEstado.getText());
            imovel.setCep(txtCep.getText());

            if (proprietarioSelecionado instanceof ClienteModel cliente) {

                ClienteModel clienteManaged = new ClienteDao()
                        .buscarPorId(cliente.getId());

                imovel.setProprietario(clienteManaged);
            }

            imovel.setResponsavel(txtResponsavel.getText());

            imovel.setDataEntrada(txtDtEntrada.getText());
            imovel.setValidadeContrato(txtValidade.getText());

            imovel.setValor(txtValor.getText());
            imovel.setValorAdministracao(txtAdm.getText());
            imovel.setValorCondominio(txtValorCond.getText());
            imovel.setValorIptu(txtValorIptu.getText());

            imovel.setApresentacao(taApresentacao.getText());
            imovel.setNegociacao(taNegociacao.getText());

            imovel.setDormitorios(parseInt(txtDorm.getText()));
            imovel.setSalas(parseInt(txtSl.getText()));
            imovel.setBanheiros(parseInt(txtBanh.getText()));
            imovel.setSuites(parseInt(txtSuite.getText()));
            imovel.setLavanderia(parseInt(txtLav.getText()));
            imovel.setVagasGaragem(parseInt(txtGar.getText()));
            imovel.setSacada(parseInt(txtSac.getText()));

            imovel.setPatio(rbPatio.isSelected());
            imovel.setVaranda(rbVaranda.isSelected());
            imovel.setGradeado(rbGradeado.isSelected());
            imovel.setMurado(rbMurado.isSelected());
            imovel.setAlarme(rbAlarme.isSelected());
            imovel.setQuiosqueCasa(rbQuiosqueCasa.isSelected());
            imovel.setCanil(rbCanil.isSelected());
            imovel.setPortao(rbPortao.isSelected());

            imovel.setElevador(rbElevador.isSelected());
            imovel.setPortaria(rbPortaria.isSelected());
            imovel.setPorteiro(rbPorteiro.isSelected());
            imovel.setPiscinaCond(rbPiscinaCond.isSelected());
            imovel.setQuiosqueCond(rbQuiosqueCond.isSelected());
            imovel.setPlayground(rbPlayground.isSelected());
            imovel.setSalaoFestas(rbSalaoFestas.isSelected());
            imovel.setBrinquedoteca(rbBrinquedoteca.isSelected());
            imovel.setQuadraEsportes(rbQuadraEsportes.isSelected());
            imovel.setChurrasqueira(rbchurrasqueira.isSelected());
            imovel.setLavanderiaCond(rbLavanderiaCon.isSelected());
            imovel.setAcademia(rbAcademia.isSelected());
            imovel.setEspacoPet(rbEspacoPet.isSelected());
            imovel.setCoworking(rbCoworking.isSelected());

            imovel.setAreaTotal(parseBigDecimal(txtArPriv.getText()));
            imovel.setAreaPrivativa(parseBigDecimal(txtArTot.getText()));
            imovel.setAreaTerreno(parseBigDecimal(txtArLt.getText()));

            ImovelDao dao = new ImovelDao();
            dao.salvar(imovel);

            JOptionPane.showMessageDialog(this, "Imóvel salvo com sucesso!");

            Navegador.abrirTela(this, new ListaImovelView(), alterado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private Integer parseInt(String valor) {
        try {
            if (valor == null || valor.trim().isEmpty()) {
                return null;
            }
            return Integer.parseInt(valor.trim());
        } catch (Exception e) {
            return null;
        }
    }

    private java.math.BigDecimal parseBigDecimal(String valor) {
        try {
            if (valor == null || valor.trim().isEmpty()) {
                return null;
            }
            return new java.math.BigDecimal(valor.replace(",", ".").trim());
        } catch (Exception e) {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAddFotos;
    private javax.swing.JButton btnAddDocs;
    private javax.swing.JButton btnCancelarImovel;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnSalvarImovel;
    private javax.swing.JComboBox<String> cbxStatusImovel;
    private javax.swing.JComboBox<String> cbxTipoImovel;
    private javax.swing.JComboBox<String> cbxTransacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCriativos;
    private javax.swing.JLabel lblImoveis;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinhaPagina;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JRadioButton rbAcademia;
    private javax.swing.JRadioButton rbAlarme;
    private javax.swing.JRadioButton rbBrinquedoteca;
    private javax.swing.JRadioButton rbCamera;
    private javax.swing.JRadioButton rbCanil;
    private javax.swing.JRadioButton rbCoworking;
    private javax.swing.JRadioButton rbElevador;
    private javax.swing.JRadioButton rbEspacoPet;
    private javax.swing.JRadioButton rbGradeado;
    private javax.swing.JRadioButton rbLavanderiaCon;
    private javax.swing.JRadioButton rbMurado;
    private javax.swing.JRadioButton rbPatio;
    private javax.swing.JRadioButton rbPiscinaCasa;
    private javax.swing.JRadioButton rbPiscinaCond;
    private javax.swing.JRadioButton rbPlayground;
    private javax.swing.JRadioButton rbPortao;
    private javax.swing.JRadioButton rbPortaria;
    private javax.swing.JRadioButton rbPorteiro;
    private javax.swing.JRadioButton rbQuadraEsportes;
    private javax.swing.JRadioButton rbQuiosqueCasa;
    private javax.swing.JRadioButton rbQuiosqueCond;
    private javax.swing.JRadioButton rbSalaoFestas;
    private javax.swing.JRadioButton rbVaranda;
    private javax.swing.JRadioButton rbchurrasqueira;
    private javax.swing.JTextArea taApresentacao;
    private javax.swing.JTextArea taNegociacao;
    private javax.swing.JTextField txtAdm;
    private javax.swing.JTextField txtArLt;
    private javax.swing.JTextField txtArPriv;
    private javax.swing.JTextField txtArTot;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBanh;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDorm;
    private javax.swing.JTextField txtDtEntrada;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtGar;
    private javax.swing.JTextField txtIdGar;
    private javax.swing.JTextField txtLav;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtSac;
    private javax.swing.JTextField txtSl;
    private javax.swing.JTextField txtSuite;
    private javax.swing.JTextField txtValidade;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorCond;
    private javax.swing.JTextField txtValorIptu;
    // End of variables declaration//GEN-END:variables
}
