package view;

import java.awt.Color;
import util.Navegador;
import dao.ClienteDao;
import model.ClientePfModel;
import model.ClientePjModel;

import java.util.List;

import javax.swing.table.DefaultTableModel;
import model.ClienteModel;

/**
 *
 * @author Maikon
 */
public class SelecionarClienteView extends javax.swing.JFrame {

    private boolean alterado = false;
    private NovoImovelView telaOrigem;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelecionarClienteView.class.getName());

    /**
     * Creates new form ListaImovelView
     */
    public SelecionarClienteView() {
        initComponents();
        configurarDuploClique();
        carregarTabela();

        tblCliente.getColumnModel()
                .getColumn(0)
                .setMinWidth(0);

        tblCliente.getColumnModel()
                .getColumn(0)
                .setMaxWidth(0);

        tblCliente.getColumnModel()
                .getColumn(0)
                .setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        lblImoveis = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        lblCriativos = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        lblMinhaPagina = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbxTipoCliente = new javax.swing.JComboBox<>();
        btnbuscarCliente = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNovoCliente = new javax.swing.JButton();
        panelLista = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMenu.setPreferredSize(new java.awt.Dimension(220, 0));

        lblImoveis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImoveis.setText("IMÓVEIS");
        lblImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImoveisMouseClicked(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo120x120.png"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClientes.setText("CLIENTES");
        lblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
        });

        lblAgenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAgenda.setText("MINHA AGENDA");
        lblAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendaMouseClicked(evt);
            }
        });

        lblCriativos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCriativos.setText("CRIATIVOS");
        lblCriativos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCriativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCriativosMouseClicked(evt);
            }
        });

        lblRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRelatorios.setText("RELATÓRIOS");
        lblRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelatoriosMouseClicked(evt);
            }
        });

        lblMinhaPagina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinhaPagina.setText("MINHA PÁGINA");
        lblMinhaPagina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinhaPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinhaPaginaMouseClicked(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuarios.setText("USUÁRIOS");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImoveis)
                    .addComponent(lblAgenda)
                    .addComponent(lblMinhaPagina)
                    .addComponent(lblRelatorios)
                    .addComponent(lblCriativos)
                    .addComponent(lblClientes))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImoveis)
                .addGap(18, 18, 18)
                .addComponent(lblClientes)
                .addGap(18, 18, 18)
                .addComponent(lblCriativos)
                .addGap(12, 12, 12)
                .addComponent(lblAgenda)
                .addGap(18, 18, 18)
                .addComponent(lblMinhaPagina)
                .addGap(18, 18, 18)
                .addComponent(lblRelatorios)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarios)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        cbxTipoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pessoa Física", "Pessoa Jurídica" }));
        cbxTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoClienteActionPerformed(evt);
            }
        });

        btnbuscarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnbuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarCliente.setText("Buscar");
        btnbuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarClienteActionPerformed(evt);
            }
        });

        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("CPF/CNPJ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefone");

        txtCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tipo Cliente");

        btnNovoCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnNovoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoCliente.setText("Novo Cliente");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNovoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNovoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscarCliente)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelLista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panelLista.setLayout(new java.awt.BorderLayout());

        tblCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 221, 221), 1, true));
        tblCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome/Razão Social", "CPF/CNPJ", "Telefone", "Email"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCliente);

        panelLista.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BUSCA DE CLIENTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImoveisMouseClicked
        Navegador.abrirTela(this, new ListaImovelView(), alterado);
    }//GEN-LAST:event_lblImoveisMouseClicked

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
        Navegador.abrirTela(this, new SelecionarClienteView(), alterado);
    }//GEN-LAST:event_lblClientesMouseClicked

    private void lblCriativosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriativosMouseClicked
        Navegador.abrirTela(this, new CriativosView(), alterado);
    }//GEN-LAST:event_lblCriativosMouseClicked

    private void lblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMouseClicked
        Navegador.abrirTela(this, new AgendaView(), alterado);
    }//GEN-LAST:event_lblAgendaMouseClicked

    private void lblMinhaPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinhaPaginaMouseClicked
        Navegador.abrirTela(this, new MinhaPaginaView(), alterado);
    }//GEN-LAST:event_lblMinhaPaginaMouseClicked

    private void lblRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelatoriosMouseClicked
        Navegador.abrirTela(this, new RelatoriosView(), alterado);
    }//GEN-LAST:event_lblRelatoriosMouseClicked

    private void cbxTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoClienteActionPerformed

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        new NovoClienteModal().setVisible(true);
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnbuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarClienteActionPerformed
        buscarClientes();
    }//GEN-LAST:event_btnbuscarClienteActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked

    }//GEN-LAST:event_tblClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelecionarClienteView().setVisible(true));
    }

    public SelecionarClienteView(NovoImovelView telaOrigem) {

        initComponents();

        this.telaOrigem = telaOrigem;

        configurarDuploClique();
        carregarTabela();
        
    }

    private void configurarDuploClique() {

        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {

                if (evt.getClickCount() == 2) {

                    int linha = tblCliente.getSelectedRow();

                    if (linha < 0) {
                        return;
                    }

                    Long id = Long.valueOf(
                            tblCliente.getValueAt(linha, 0).toString()
                    );

                    ClienteDao dao = new ClienteDao();

                    ClienteModel cliente = dao.buscarPorId(id);

                    telaOrigem.setProprietarioSelecionado(cliente);

                    dispose();
                }
            }
        });
    }

    private void carregarTabela() {

        ClienteDao dao = new ClienteDao();

        DefaultTableModel modelo
                = (DefaultTableModel) tblCliente.getModel();

        modelo.setRowCount(0);

        List<ClientePfModel> listaPf = dao.listarPf();

        for (ClientePfModel cliente : listaPf) {

            modelo.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getCpf(),
                cliente.getTelefone(),
                cliente.getEmail()
            });

        }

        List<ClientePjModel> listaPj = dao.listarPj();

        for (ClientePjModel cliente : listaPj) {

            modelo.addRow(new Object[]{
                cliente.getId(),
                cliente.getRazaoSocial(),
                cliente.getCnpj(),
                cliente.getTelefone(),
                cliente.getEmail()
            });

        }

    }

    private void buscarClientes() {

        ClienteDao dao = new ClienteDao();

        DefaultTableModel modelo
                = (DefaultTableModel) tblCliente.getModel();

        modelo.setRowCount(0);

        String nome = txtNomeCliente.getText();
        String cpfCnpj = txtCpfCnpj.getText();
        String telefone = txtTelefone.getText();

        String tipo = cbxTipoCliente
                .getSelectedItem()
                .toString();

        if (tipo.equals("Todos")
                || tipo.equals("Pessoa Física")) {

            for (ClientePfModel cliente
                    : dao.buscarPf(
                            nome,
                            cpfCnpj,
                            telefone)) {

                modelo.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNome(),
                    cliente.getCpf(),
                    cliente.getTelefone(),
                    cliente.getEmail()
                });
            }
        }

        if (tipo.equals("Todos")
                || tipo.equals("Pessoa Jurídica")) {

            for (ClientePjModel cliente
                    : dao.buscarPj(
                            nome,
                            cpfCnpj,
                            telefone)) {

                modelo.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getRazaoSocial(),
                    cliente.getCnpj(),
                    cliente.getTelefone(),
                    cliente.getEmail()
                });
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnbuscarCliente;
    private javax.swing.JComboBox<String> cbxTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCriativos;
    private javax.swing.JLabel lblImoveis;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinhaPagina;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
